### ISSUE TITLE
J'ai beaucoup aimé mais malheureusement.... 

### ISSUE THREAD

**Issue by fusetim** [Adem-hub/ProjetOcaml#1]
Beaucoup aimé le jeu mais pour luncher je ne mettrais que 4/5 étoiles.
https://github.com/Adem-hub/ProjetOcaml/blob/main/README.md#L91

**Comment by ThomasCreuset** [comment]
Merci de votre commentaire, l'erreur à été corrigée, si vous rencontrer quelconques autres problèmes n'hésiter pas à la signaler.

**Comment by fusetim** [comment]
Super merci :)
